# Site settings
title: t3hmun
description: "t3hmun's personal blog."
baseurl: "http://t3hmun.github.io" # full path of the site

# There is no need for the excessively long urls used by default.
permalink: "/:categories/:year/:title/"

# Build settings
markdown: kramdown
kramdown:
  input: GFM # GithHub Flavored Markdown, support for Github style fenced code blocks.
  syntax_highlighter: rouge
  hard_wrap: false # Single line breaks are ignored as in standard Markdown.
  header_offset: 1 # <h#> tags are offset down by one size.